ALTER TABLE rfq_records
  ADD COLUMN IF NOT EXISTS country VARCHAR(2),
  ADD COLUMN IF NOT EXISTS region VARCHAR(128),
  ADD COLUMN IF NOT EXISTS industry VARCHAR(128),
  ADD COLUMN IF NOT EXISTS duration_hours NUMERIC(8, 2),
  ADD COLUMN IF NOT EXISTS utm_medium VARCHAR(128),
  ADD COLUMN IF NOT EXISTS utm_content VARCHAR(128),
  ADD COLUMN IF NOT EXISTS utm_term VARCHAR(128),
  ADD COLUMN IF NOT EXISTS referrer TEXT,
  ADD COLUMN IF NOT EXISTS landing_page TEXT,
  ADD COLUMN IF NOT EXISTS locale VARCHAR(10),
  ADD COLUMN IF NOT EXISTS selected_products JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS calculation_id VARCHAR(64),
  ADD COLUMN IF NOT EXISTS crm_sync_status VARCHAR(16) NOT NULL DEFAULT 'PENDING';
