UPDATE users SET role = 'VIEWER' WHERE role = 'READ_ONLY';

ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_allowed;
ALTER TABLE users ADD CONSTRAINT users_role_allowed CHECK (role IN (
  'SUPER_ADMIN', 'ADMIN', 'ENGINEER', 'PRODUCT_MANAGER', 'CONTENT_MANAGER',
  'TRANSLATOR', 'SALES', 'PARTNER', 'CUSTOMER', 'VIEWER'
));
