import Link from 'next/link';import {notFound} from 'next/navigation';import type {Metadata} from 'next';import {ArrowRight,BookOpen,Building2,FileText,ShieldCheck} from 'lucide-react';import {LoginForm} from '../../../components/LoginForm';import {LocalizedUnavailable} from '../../../components/LocalizedUnavailable';
export const dynamic='force-dynamic';
type PageInfo={title:string;intro:string;items?:string[];links?:[string,string][];note?:string};
const pages:Record<string,PageInfo>={
 'login':{title:'Вхід до кабінету',intro:'Захищений доступ для користувачів, створених адміністратором.'},
 'catl-ukraine':{title:'CATL Energy Storage в Україні',intro:'Ця сторінка описує інформаційний ресурс KATL про системи накопичення енергії CATL. Наявні матеріали репозиторію не підтверджують юридичний статус офіційного представника, дистриб’ютора або авторизованого сервісного партнера.',items:['KATL не заявляє офіційне представництво без документального підтвердження.','Точні продукти, ціни, сертифікати, гарантії й умови постачання публікуються лише після перевірки джерела та прав на використання.','Запит щодо конкретної моделі можна передати через RFQ; доступність підтверджується окремо.'],note:'Публічна сторінка потребує юридичних реквізитів і затвердженого опису правовідносин до production.'},
 'energy-storage-ukraine':{title:'Системи накопичення енергії в Україні',intro:'BESS-проєкт в Україні потребує оцінки профілю навантаження, точки приєднання, режиму роботи та застосовних технічних і регуляторних вимог.',items:['Зберіть інтервальні дані споживання й генерації.','Уточніть параметри приєднання та обмеження оператора мережі.','Визначте, які навантаження є критичними й який час автономії потрібен.','Перевірте вимоги до сертифікації, монтажу, пожежної безпеки та дозволів із компетентними фахівцями.'],note:'Регуляторна інформація потребує перевірки за чинними першоджерелами для кожного проєкту.'},
 'about':{title:'Про KATL',intro:'KATL — назва цієї цифрової платформи для інформації, інженерних інструментів і запитів щодо BESS.',items:['Юридична особа, адреса та контактні реквізити оператора сайту ще мають бути додані з підтверджених даних.','Команда не заявляє про авторизацію CATL, локальний офіс, кейси чи сервісну мережу без підтвердження.','Технічні матеріали мають посилатися на актуальні першоджерела та дату перевірки.'],note:'До публікації потрібні дані оператора сайту, privacy/terms і погоджений опис партнерського статусу.'},
 'partners':{title:'Партнерська програма',intro:'Партнерська модель, територіальні права, умови реєстрації угод і комісії не підтверджені в наявних матеріалах.',items:['Інтегратори, EPC-компанії та інженерні фірми можуть надіслати запит про співпрацю.','Не надсилайте персональні дані клієнта без належної правової підстави та згоди.','Портал партнерських угод і статусів ще не доступний.'],links:[['Надіслати запит','/uk-UA/contact'],['Увійти до кабінету','/uk-UA/login']]},
 'contact':{title:'Контакти',intro:'Для зв’язку з командою проєкту надішліть запит через форму. Публічні телефон, адреса офісу та юридичні реквізити не вказуються до їх підтвердження.',links:[['Створити запит пропозиції','/uk-UA/rfq'],['Партнерство','/uk-UA/partners']],note:'Не використовуйте цю форму для аварійних звернень або сервісного обслуговування обладнання.'},
 'resources':{title:'База знань BESS',intro:'Пояснення базових термінів і підготовка вихідних даних для інженерної оцінки. Матеріали не замінюють проєктну документацію або інструкції виробника.',links:[['Що таке BESS','/uk-UA/bess'],['Як підготувати вимоги до системи','/uk-UA/resources/guides/how-to-choose-bess'],['Глосарій','/uk-UA/resources/glossary'],['Документи','/uk-UA/documents']]},
 'resources/guides/how-to-choose-bess':{title:'Як підготувати вимоги до BESS',intro:'Підбір системи починається з профілю об’єкта, а не з назви моделі.',items:['Підготуйте 15-хвилинні або погодинні дані навантаження за типовий період.','Виділіть критичні споживачі, пускові режими та допустимий час перерви.','Опишіть джерела генерації, точку приєднання, напругу та доступну потужність.','Сформулюйте ціль: резерв, peak shaving, самоспоживання, перенесення енергії чи інший сценарій.','Запросіть datasheet, інструкції, сертифікати, умови гарантії й перелік сумісних компонентів для конкретної конфігурації.'],links:[['BESS Calculator','/uk-UA/engineering/bess-calculator'],['Створити RFQ','/uk-UA/rfq']]},
 'resources/glossary':{title:'Глосарій BESS',intro:'Короткі визначення термінів, що часто зустрічаються в описах систем накопичення енергії.',links:[['BESS','/uk-UA/resources/glossary/bess'],['SOC','/uk-UA/resources/glossary/soc'],['SOH','/uk-UA/resources/glossary/soh'],['C-rate','/uk-UA/resources/glossary/c-rate'],['DoD','/uk-UA/resources/glossary/dod'],['LCOS','/uk-UA/resources/glossary/lcos'],['PCS','/uk-UA/resources/glossary/pcs'],['EMS','/uk-UA/resources/glossary/ems'],['BMS','/uk-UA/resources/glossary/bms']]},
 'resources/glossary/bess':{title:'BESS',intro:'Battery Energy Storage System — система накопичення електричної енергії на основі батарей і пов’язаних компонентів керування, перетворення, захисту та підключення.',links:[['Повний огляд BESS','/uk-UA/bess'],['Калькулятор','/uk-UA/engineering/bess-calculator']]},
 'resources/glossary/soc':{title:'SOC — State of Charge',intro:'Оцінка поточного рівня заряду батареї відносно визначеної шкали. Точне трактування, діапазон і точність залежать від батарейної системи та її BMS.'},
 'resources/glossary/soh':{title:'SOH — State of Health',intro:'Оцінка стану батареї відносно визначеного початкового або номінального стану. Методи розрахунку залежать від виробника та системи моніторингу.'},
 'resources/glossary/c-rate':{title:'C-rate',intro:'Відношення струму заряджання або розряджання до номінальної ємності батареї. Інтерпретувати значення потрібно разом із паспортом конкретної моделі.'},
 'resources/glossary/dod':{title:'DoD — Depth of Discharge',intro:'Частка номінального запасу енергії, яку було використано під час розряджання. Допустимий діапазон визначається документацією батарейної системи.'},
 'resources/glossary/lcos':{title:'LCOS — Levelized Cost of Storage',intro:'Метрика, що співвідносить приведені витрати системи накопичення з енергією, відданою за розрахунковий період. Результат залежить від повноти CAPEX/OPEX, профілю циклів, деградації, ефективності та ставки дисконтування.',links:[['Калькулятор LCOS','/uk-UA/engineering/lcos']]},
 'resources/glossary/pcs':{title:'PCS — Power Conversion System',intro:'Силова електроніка, що керує обміном потужністю між DC-частиною батареї та AC-мережею або навантаженням. Конкретні режими залежать від обладнання та проєкту.'},
 'resources/glossary/ems':{title:'EMS — Energy Management System',intro:'Система верхнього рівня, що координує режими енергетичної установки відповідно до налаштованих цілей, обмежень і сигналів.'},
 'resources/glossary/bms':{title:'BMS — Battery Management System',intro:'Система моніторингу й керування батареєю, що збирає вимірювання та контролює робочі межі згідно з документацією виробника.'},
 'bess-price':{title:'Вартість BESS в Україні',intro:'Ціна системи залежить від потужності, енергетичної ємності, PCS, трансформатора, систем керування, захистів, монтажу, введення в експлуатацію та умов приєднання.',items:['У доступних матеріалах немає підтверджених актуальних цінових діапазонів.','Ми не публікуємо вигадані ціни або терміни окупності.','Для попереднього кошторису потрібні параметри майданчика й бажаний режим роботи.'],links:[['Підготувати параметри','/uk-UA/engineering/bess-calculator'],['Запросити ціну','/uk-UA/rfq']]},
 'engineering':{title:'Інженерні інструменти для BESS',intro:'Почніть із розрахунку потужності й енергії. Економічні інструменти будуть доступні після формалізації джерел тарифів, CAPEX/OPEX і профілів циклів.',links:[['BESS Calculator','/uk-UA/engineering/bess-calculator'],['LCOS — методика та калькулятор','/uk-UA/engineering/lcos'],['BESS Designer','/uk-UA/bess-designer']]},
 'engineering/lcos':{title:'Калькулятор LCOS',intro:'Повний калькулятор LCOS ще проходить підготовку. До його публікації потрібні перевірювані входи: CAPEX, OPEX, cycles, degradation, efficiency, lifetime та discount rate.',note:'Не використовуємо демо-значення або приховані ринкові припущення.'},
 'engineering/roi':{title:'ROI калькулятор BESS',intro:'ROI залежить від тарифів, режиму диспетчеризації, доступності системи та витрат життєвого циклу. Калькулятор буде опублікований після затвердження джерел і методики.',note:'У репозиторії поки немає підтверджених цін або тарифних даних для фінансової оцінки.'},
 'engineering/backup-runtime':{title:'Калькулятор часу резерву',intro:'Базова оцінка runtime потребує корисної енергії системи, навантаження, ефективності перетворення та граничної глибини розряду з паспорта обладнання.',links:[['BESS Calculator','/uk-UA/engineering/bess-calculator']]},
 'engineering/solar-bess':{title:'Solar + BESS: оцінка параметрів',intro:'Почніть із погодинних даних генерації та споживання. Простий розрахунок лише за встановленими kWp не показує часову відповідність профілів.'},
 'engineering/peak-shaving':{title:'Peak shaving: оцінка навантаження',intro:'Для оцінки потрібні інтервальні вимірювання навантаження та тарифне правило формування пікової потужності.'},
 'engineering/diesel-vs-bess':{title:'Порівняння генератора й BESS',intro:'Коректне порівняння потребує реальної витрати пального під навантаженням, ціни пального, графіка роботи, CAPEX, OPEX і режиму обслуговування.'},
 'bess-designer':{title:'BESS Designer',intro:'Designer зараз підтримує початкову оцінку потрібної енергії та потужності. Збереження проєкту, PDF, автоматична комплектація та рекомендація моделі ще не підключені.',links:[['Відкрити BESS Calculator','/uk-UA/engineering/bess-calculator'],['Передати параметри інженеру','/uk-UA/rfq']],note:'Ми не підміняємо відсутні паспортні параметри або сумісність типовою конфігурацією.'},
 'privacy':{title:'Політика приватності',intro:'Перед публічним запуском оператор сайту має додати юридично перевірену політику обробки персональних даних, контакти відповідальної особи, строки зберігання, підстави обробки та процедуру звернення.'},
 'terms':{title:'Умови використання',intro:'Юридично перевірені умови використання й обмеження відповідальності мають бути додані оператором сайту до production-публікації.'},
};

export async function generateMetadata({params}:{params:Promise<{locale:string;segments?:string[]}>}):Promise<Metadata>{const {locale,segments=[]}=await params;const item=pages[segments.join('/')];if(locale!=='uk-UA')return {title:locale==='zh-CN'?'页面本地化审核中':'Localization review pending',robots:{index:false,follow:false}};return item?{title:item.title,description:item.intro,alternates:{canonical:`/${locale}/${segments.join('/')}`},...(segments.join('/')==='login'?{robots:{index:false,follow:false}}:{})}:{title:'Сторінку не знайдено',robots:{index:false,follow:false}};}

export default async function ContentRoute({params}:{params:Promise<{locale:string;segments?:string[]}>}){const {locale,segments=[]}=await params;const path=segments.join('/');const item=pages[path];if(!['uk-UA','en','zh-CN'].includes(locale))notFound();if(locale!=='uk-UA')return <LocalizedUnavailable locale={locale}/>;if(!item)notFound();
 if(path==='login')return <main><section className="page-hero"><div className="container"><div className="eyebrow">ОСОБИСТИЙ КАБІНЕТ</div><h1>Вхід до кабінету</h1><p>Захищений доступ для зареєстрованих клієнтів, партнерів і команди.</p></div></section><section className="content-section"><LoginForm/></section></main>;
 return <main><section className="page-hero"><div className="container"><div className="breadcrumbs"><Link href={`/${locale}`}>Головна</Link>　/　{segments.join(' / ')}</div><div className="eyebrow">{path.startsWith('resources')?'БАЗА ЗНАНЬ':path.startsWith('engineering')?'ІНЖЕНЕРІЯ':'KATL · CATL ENERGY STORAGE'}</div><h1>{item.title}</h1><p>{item.intro}</p></div></section><section className="content-section"><div className="container" style={{maxWidth:900}}>{item.items&&<div className="calc-card"><h2>Що варто врахувати</h2><ul>{item.items.map(text=><li key={text}>{text}</li>)}</ul></div>}{item.links&&<div className="journey-grid" style={{marginTop:16}}>{item.links.map(([label,href])=><Link className="journey-card" href={href.replace('/uk-UA',`/${locale}`)} key={label}><span className="icon-box"><BookOpen size={20}/></span><h2 style={{fontSize:16}}>{label}</h2><p>Перейти до пов’язаної сторінки або інструмента.</p><span className="card-arrow">→</span></Link>)}</div>}{item.note&&<p className="status-note" style={{marginTop:18}}>{item.note}</p>}{!item.items&&!item.links&&!item.note&&<div className="empty-state"><FileText color="#1769d2"/><div><h3>Матеріал у підготовці</h3><p>Публічні технічні відомості з’являться після перевірки джерела та редакційного погодження.</p></div></div>}{path==='catl-ukraine'&&<div className="status-note" style={{marginTop:18}}><ShieldCheck size={17}/> Юридичні відносини KATL і CATL не підтверджені матеріалами проєкту; сайт не заявляє статус офіційного представника.</div>}{path==='partners'&&<div className="status-note" style={{marginTop:18}}><Building2 size={17}/> Партнерський кабінет і deal registration ще не доступні.</div>}<div className="cta-panel" style={{marginTop:24}}><div><h2>Потрібне уточнення для проєкту?</h2><p>Передайте параметри майданчика для наступного кроку.</p></div><Link className="button" href={`/${locale}/rfq`}>Створити RFQ <ArrowRight size={15}/></Link></div></div></section></main>}
