import Link from 'next/link';import type {Metadata} from 'next';import {notFound} from 'next/navigation';import {ArrowRight,Sun,Zap,Gauge,BatteryCharging,Network,Factory} from 'lucide-react';
const content:Record<string,{title:string;summary:string;problem:string;inputs:string[];links:string[]}>={
 'solar-bess':{title:'Сонячна енергетика + BESS',summary:'Як оцінити взаємодію фотоелектричної генерації, накопичення, навантаження та мережі на одному майданчику.',problem:'Профіль генерації СЕС не завжди збігається з графіком споживання. Накопичення може змінити час використання енергії, але результат залежить від навантаження, мережевих правил і параметрів системи.',inputs:['Погодинний профіль генерації та споживання','Обмеження експорту й умови приєднання','Потрібна потужність і час віддачі','Режим роботи та резерв для критичних навантажень'],links:['BESS Calculator','BESS Designer','Документи']},
 'peak-shaving':{title:'Peak shaving для підприємства',summary:'Оцініть, чи може накопичення впливати на піки потужності з урахуванням графіка навантаження.',problem:'Для попередньої оцінки потрібні інтервали вимірювання навантаження та правила, за якими формується плата за потужність. Одного місячного значення споживання недостатньо.',inputs:['Інтервальні дані навантаження','Період і тривалість пікових подій','Доступна потужність мережі','Тарифна структура та вимоги до резерву'],links:['BESS Calculator','Інженерна оцінка','RFQ']},
 'backup-power':{title:'Резервне живлення',summary:'Почніть із критичних навантажень, часу автономії та допустимого переходу між джерелами.',problem:'Резервування вимагає узгодження характеристик навантаження, часу перемикання, режиму роботи PCS, захистів і наявних генераторів.',inputs:['Перелік критичних споживачів і їх пускові струми','Бажаний час автономії','Допустимий час перерви','Наявність UPS або генератора'],links:['BESS Calculator','BESS Designer','RFQ']},
 'energy-arbitrage':{title:'Арбітраж енергії',summary:'Оцініть цикли заряджання та віддачі на основі погодинних цін, обмежень мережі й ефективності.',problem:'Економічний результат не можна визначити без профілю цін, правил ринку, доступу до торгівлі, вартості втрат і деградації.',inputs:['Погодинна структура цін','Доступні режими заряджання','ККД і технічні обмеження з підтверджених джерел','Витрати на обслуговування й балансування'],links:['LCOS','BESS Calculator','RFQ']},
 'microgrid':{title:'BESS для мікромережі',summary:'Архітектуру визначають джерела, навантаження, режим острова, система керування та схема захистів.',problem:'Острівна робота й синхронізація з мережею мають бути підтверджені сумісністю конкретних компонентів і проєктним розрахунком.',inputs:['Однолінійна схема майданчика','Джерела генерації та їх режими','Критичні навантаження','Вимоги до резервування та переходу в острів'],links:['BESS Designer','Інженерія','RFQ']},
 'ev-charging':{title:'BESS для зарядної інфраструктури',summary:'Оцініть піковий попит швидких зарядних станцій у межах доступної потужності приєднання.',problem:'Потрібно врахувати одночасність заряджання, графік сесій, потужність мережі, генерацію та очікуваний розвиток локації.',inputs:['Кількість і потужність зарядних точок','Профіль сесій і одночасність','Доступна потужність приєднання','План розвитку майданчика'],links:['BESS Calculator','Рішення для підприємств','RFQ']},
};
export async function generateMetadata({params}:{params:Promise<{locale:string;slug:string}>}):Promise<Metadata>{const {slug}=await params;return {title:content[slug]?.title||'Рішення BESS',description:content[slug]?.summary};}
export default async function SolutionDetail({params}:{params:Promise<{locale:string;slug:string}>}){const {locale,slug}=await params;const item=content[slug];if(!item||locale!=='uk-UA')notFound();const Icon=slug==='solar-bess'?Sun:slug==='peak-shaving'?Gauge:slug==='backup-power'?Zap:slug==='microgrid'?Network:slug==='ev-charging'?Factory:BatteryCharging;return <main><section className="page-hero"><div className="container"><div className="breadcrumbs"><Link href={`/${locale}`}>Головна</Link>　/　<Link href={`/${locale}/solutions`}>Рішення</Link>　/　{item.title}</div><span className="icon-box"><Icon size={22}/></span><h1>{item.title}</h1><p>{item.summary}</p><div className="hero-actions"><Link className="button" href={`/${locale}/engineering/bess-calculator`}>Оцінити параметри <ArrowRight size={15}/></Link><Link className="button button-secondary" href={`/${locale}/rfq`}>Створити інженерний запит</Link></div></div></section><section className="content-section"><div className="container" style={{maxWidth:920}}><article className="prose"><h2>Що потрібно врахувати</h2><p>{item.problem}</p><h2>Дані для попереднього підбору</h2><ul>{item.inputs.map(input=><li key={input}>{input}</li>)}</ul><h2>Наступні кроки</h2><div className="journey-grid">{item.links.map(link=><Link key={link} className="journey-card" href={link==='RFQ'?`/${locale}/rfq`:link==='LCOS'?`/${locale}/engineering/lcos`:link==='Документи'?`/${locale}/documents`:link.includes('BESS')||link==='Інженерія'?`/${locale}/engineering`: `/${locale}/engineering/bess-calculator`}><h3>{link}</h3><p>Перейдіть до інструмента або надішліть параметри майданчика.</p><span className="card-arrow">→</span></Link>)}</div><p className="status-note">Сторінка містить загальну інженерну інформацію. Конкретний CATL продукт, сумісність і фінансова доцільність підтверджуються після аналізу джерел і майданчика.</p></article></div></section></main>}
