import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ArrowRight, BatteryCharging, CircleHelp, Gauge, Network, ShieldCheck, Zap } from 'lucide-react';
import { LocalizedUnavailable } from '../../../components/LocalizedUnavailable';

export const metadata:Metadata={title:'BESS — системи накопичення енергії',description:'Що таке BESS: компоненти, потужність і ємність, сценарії застосування та питання для інженерного підбору.'};
export default async function BessHub({params}:{params:Promise<{locale:string}>}){
 const {locale}=await params;if(locale!=='uk-UA')notFound();if(locale!=='uk-UA')return <LocalizedUnavailable locale={locale}/>;
 return <main><section className="page-hero"><div className="container"><div className="breadcrumbs"><Link href={`/${locale}`}>Головна</Link>　/　База знань　/　BESS</div><div className="eyebrow">ОСНОВИ НАКОПИЧЕННЯ ЕНЕРГІЇ</div><h1>BESS — системи накопичення енергії</h1><p><strong>BESS</strong> (Battery Energy Storage System) — система, що зберігає електричну енергію в акумуляторних батареях і віддає її пізніше відповідно до режиму керування, обмежень обладнання та вимог електричної мережі.</p><div className="hero-actions"><Link className="button" href={`/${locale}/engineering/bess-calculator`}>Оцінити параметри <ArrowRight size={15}/></Link><Link className="button button-secondary" href={`/${locale}/rfq`}>Обговорити проєкт</Link></div></div></section>
 <section className="content-section"><div className="container" style={{display:'grid',gridTemplateColumns:'minmax(0,1fr) 250px',gap:55}}><article className="prose"><h2 id="how">Як працює BESS</h2><p>Під час заряджання перетворювач приймає електроенергію від мережі або генерації та передає її батарейним модулям. Під час розряджання енергія проходить зворотний шлях через силову електроніку до навантаження або точки приєднання. Фактична схема залежить від обладнання, захистів, режиму мережі та проєктних вимог.</p>
 <h2 id="components">Основні компоненти</h2><ul><li><strong>Акумуляторна система</strong> — комірки, модулі, стійки або шафи.</li><li><strong>PCS</strong> — двонаправлений перетворювач потужності.</li><li><strong>BMS</strong> — моніторинг стану батареї та обмеження робочих режимів.</li><li><strong>EMS</strong> — керування енергетичними потоками на рівні системи.</li><li><strong>Тепловий режим і захист</strong> — інженерні підсистеми, що визначаються вимогами майданчика та документацією постачальників.</li><li><strong>Приєднання до мережі</strong> — трансформаторне обладнання, комутація, вимірювання й захисти за проєктом.</li></ul>
 <h2 id="power-energy">MW і MWh — різні характеристики</h2><p><strong>MW</strong> описує потужність — швидкість, з якою система може приймати або віддавати енергію. <strong>MWh</strong> описує запас енергії. Спрощено, система потужністю 1 MW із запасом 2 MWh може віддавати номінальну потужність близько двох годин лише за ідеалізованих умов. Корисна енергія, ККД, резерви та обмеження обладнання змінюють фактичний час роботи.</p>
 <h2 id="use-cases">Де застосовують</h2><p>Можливі сценарії включають перенесення споживання в часі, зниження короткочасних піків, резервне живлення, інтеграцію з відновлюваною генерацією, зарядну інфраструктуру та мікромережі. Економічна й технічна доцільність залежить від погодинних профілів навантаження, тарифної структури, умов приєднання, режиму роботи та вартості проєкту.</p>
 <h2 id="limits">Обмеження та безпека</h2><p>Початковий розрахунок не замінює дослідження мережі, проєктування захистів, оцінки пожежних ризиків, теплового аналізу, перевірки сумісності та місцевих дозвільних процедур. До вибору обладнання необхідно отримати актуальні datasheet, інструкції та сертифікати для конкретної моделі й конфігурації.</p>
 <h2 id="economics">Економіка</h2><p>Для фінансової оцінки потрібні часові ряди споживання та генерації, правила ринку/тарифів, доступна потужність приєднання, припущення щодо циклів, деградації, ефективності, обслуговування та фінансування. Якщо цих даних немає, калькулятор має показувати лише технічну оцінку або перелік потрібних входів.</p>
 <h2 id="faq">Поширені запитання</h2><h3>Чи є MWh достатнім параметром для підбору?</h3><p>Ні. Потрібні щонайменше потужність у MW, тривалість, режим роботи та параметри точки приєднання.</p><h3>Чи може BESS замінити UPS або генератор?</h3><p>Це залежить від часу перемикання, допустимих перерв, автономності, резервування та проєктної архітектури. Таку заміну не можна припускати без окремого аналізу.</p><h3>Чи публікує KATL ціну?</h3><p>Ціна залежить від комплектації та умов майданчика. Якщо перевірених актуальних цінових даних немає, їх не підмінюємо орієнтовними сумами.</p>
 <p className="status-note">Матеріал пояснює загальні поняття і не є проєктною документацією, гарантією сумісності чи рекомендацією конкретного CATL продукту.</p></article><aside style={{position:'sticky',top:100,alignSelf:'start'}}><div className="calc-card"><strong>На цій сторінці</strong>{[['how','Як працює'],['components','Компоненти'],['power-energy','MW та MWh'],['use-cases','Застосування'],['limits','Обмеження й безпека'],['economics','Економіка'],['faq','FAQ']].map(([id,label])=><a key={id} className="footer-col" style={{display:'block',fontSize:12,padding:'8px 0',color:'#475467'}} href={`#${id}`}>{label}</a>)}</div><div className="calc-card" style={{marginTop:13}}><CircleHelp color="#1769d2"/><p style={{fontSize:12,color:'#667085'}}>Готуєте проєкт? Зберіть вихідні дані для інженерного запиту.</p><Link className="text-link" href={`/${locale}/rfq`}>Створити RFQ →</Link></div></aside></div></section>
 <section className="section section-soft"><div className="container"><div className="section-head"><div><div className="eyebrow">Далі</div><h2>Інженерні інструменти</h2></div></div><div className="tile-grid">{[[BatteryCharging,'BESS Calculator','/engineering/bess-calculator'],[Gauge,'LCOS','/engineering/lcos'],[Zap,'BESS Designer','/bess-designer'],[Network,'Рішення','/solutions']].map(([Icon,label,path])=>{const I=Icon as typeof BatteryCharging;return <Link className="tool-card" href={`/${locale}${path as string}`} key={label as string}><span className="icon-box"><I size={20}/></span><h3>{label as string}</h3><span className="text-link">Перейти →</span></Link>})}</div></div></section></main>;
}
